ProxyPreserveHost On
ProxyRequests Off

RequestHeader set X-Forwarded-Proto "https"

RedirectMatch 302 ^/PlantScNet$ /PlantScNet/

ProxyPass        /PlantScNet/api/  http://127.0.0.1:10809/api/
ProxyPassReverse /PlantScNet/api/  http://127.0.0.1:10809/api/

ProxyPass        /PlantScNet/      http://127.0.0.1:10809/PlantScNet/
ProxyPassReverse /PlantScNet/      http://127.0.0.1:10809/PlantScNet/
