export const speciesCatalog = [
  { id: 'ach', label: 'Actinidia chinensis' },
  { id: 'aly', label: 'Arabidopsis lyrata' },
  { id: 'ath', label: 'Arabidopsis thaliana' },
  { id: 'bdi', label: 'Brachypodium distachyon' },
  { id: 'bol', label: 'Brassica oleracea' },
  { id: 'bra', label: 'Brassica rapa' },
  { id: 'cas', label: 'Camelina sativa' },
  { id: 'cre', label: 'Chlamydomonas reinhardtii' },
  { id: 'cro', label: 'Crocus sativus' },
  { id: 'cru', label: 'Capsella rubella' },
  { id: 'egr', label: 'Eucalyptus grandis' },
  { id: 'esa', label: 'Eutrema salsugineum' },
  { id: 'fve', label: 'Fragaria vesca' },
  { id: 'gar', label: 'Gossypium arboreum' },
  { id: 'ghi', label: 'Gossypium hirsutum' },
  { id: 'gly', label: 'Glycine max' },
  { id: 'lja', label: 'Lotus japonicus' },
  { id: 'mes', label: 'Manihot esculenta' },
  { id: 'mtr', label: 'Medicago truncatula' },
  { id: 'osa', label: 'Oryza sativa' },
  { id: 'pha', label: 'Panicum hallii' },
  { id: 'phe', label: 'Phyllostachys edulis' },
  { id: 'ptr', label: 'Populus trichocarpa' },
  { id: 'pvu', label: 'Phaseolus vulgaris' },
  { id: 'sbi', label: 'Sorghum bicolor' },
  { id: 'sly', label: 'Solanum lycopersicum' },
  { id: 'spa', label: 'Schrenkiella parvula' },
  { id: 'svi', label: 'Setaria viridis' },
  { id: 'tae', label: 'Triticum aestivum' },
  { id: 'zea', label: 'Zea mays' },
]

export const speciesById = new Map(speciesCatalog.map((species) => [species.id, species]))
